steps:
  # Build image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA', '.']
  
  # Push ke Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA']
  
  # Deploy ke Cloud Run
  - name: 'gcr.io/cloud-builders/run'
    args:
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=2'
      - '--timeout=3600'
      - '--max-instances=100'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'

substitutions:
  _SERVICE_NAME: 'persona-ai'
  _REGION: 'asia-southeast2'

options:
  machineType: 'N1_HIGHCPU_8'

timeout: '1800s'
